@startuml
actor Actor
Actor -> ForgotPasswordServlet : main
activate ForgotPasswordServlet
' create UserModel
ForgotPasswordServlet -> UserModel : new
activate UserModel
UserModel --> ForgotPasswordServlet
deactivate UserModel
ForgotPasswordServlet -> UserModel : getByUsername
activate UserModel
UserModel -> ModelBase : connection
activate ModelBase
ModelBase -> Database : save account
activate Database
Database --> ModelBase : saved
deactivate Database
ModelBase --> UserModel
deactivate ModelBase
create User
UserModel -> User : new
activate User
User --> UserModel
deactivate User
UserModel --> ForgotPasswordServlet
deactivate UserModel
ForgotPasswordServlet -> TokenGenerator : generate
activate TokenGenerator
TokenGenerator -> Crypto : encode64
activate Crypto
Crypto --> TokenGenerator
deactivate Crypto
TokenGenerator -> Crypto : HMACSHA256
activate Crypto
Crypto -> Crypto : bytesToHex
activate Crypto
Crypto --> Crypto
deactivate Crypto
Crypto --> TokenGenerator
deactivate Crypto
TokenGenerator -> Crypto : encode64
activate Crypto
Crypto --> TokenGenerator
deactivate Crypto
TokenGenerator -> Crypto : encode64
activate Crypto
Crypto --> TokenGenerator
deactivate Crypto
TokenGenerator --> ForgotPasswordServlet
deactivate TokenGenerator
ForgotPasswordServlet -> EmailSystem : sendEmail
activate EmailSystem
' create MailRequest
EmailSystem -> MailRequest : new
activate MailRequest
MailRequest --> EmailSystem
deactivate MailRequest
' create EmailSender
EmailSystem -> EmailSender : new
activate EmailSender
EmailSender --> EmailSystem
deactivate EmailSender
EmailSystem --> ForgotPasswordServlet
deactivate EmailSystem
ForgotPasswordServlet -> TokenCache : cacheToken
activate TokenCache
TokenCache --> ForgotPasswordServlet
deactivate TokenCache
ForgotPasswordServlet -> EmailSystem : sendEmail
activate EmailSystem
' create MailRequest
EmailSystem -> MailRequest : new
activate MailRequest
MailRequest --> EmailSystem
deactivate MailRequest
' create EmailSender
EmailSystem -> EmailSender : new
activate EmailSender
EmailSender --> EmailSystem
deactivate EmailSender
EmailSystem --> ForgotPasswordServlet
deactivate EmailSystem
ForgotPasswordServlet -> TokenCache : cacheToken
activate TokenCache
TokenCache --> ForgotPasswordServlet
deactivate TokenCache
return
@enduml
