@startuml
actor Actor
Actor -> SignupServlet : register request
activate SignupServlet
SignupServlet -> TokenGenerator : generate
activate TokenGenerator
TokenGenerator --> SignupServlet
deactivate TokenGenerator
SignupServlet -> TokenCache : main :cacheToken
activate TokenCache
TokenCache --> SignupServlet
deactivate TokenCache
SignupServlet -> EmailSystem : sendEmail
activate EmailSystem
'create MailRequest
EmailSystem -> MailRequest : new
activate MailRequest
MailRequest --> EmailSystem
deactivate MailRequest
'create EmailSender
EmailSystem -> EmailSender : new
activate EmailSender
EmailSender --> EmailSystem
deactivate EmailSender
EmailSystem --> SignupServlet
deactivate EmailSystem
'create UserModel
SignupServlet -> UserModel : new
activate UserModel
UserModel --> SignupServlet
deactivate UserModel
SignupServlet -> UserModel : createAccount
activate UserModel
UserModel -> ModelBase : connection
activate ModelBase
ModelBase --> UserModel : saved
deactivate ModelBase
TokenGenerator -> Crypto : encode64
activate Crypto
Crypto --> TokenGenerator
deactivate Crypto
TokenGenerator -> Crypto : HMACSHA256
activate Crypto
Crypto -> Crypto : bytesToHex
activate Crypto
Crypto --> Crypto
deactivate Crypto
Crypto --> TokenGenerator
deactivate Crypto
TokenGenerator -> Crypto : encode64
activate Crypto
Crypto --> TokenGenerator
deactivate Crypto
TokenGenerator -> Crypto : encode64
activate Crypto
Crypto --> TokenGenerator
deactivate Crypto
UserModel -> Crypto : SHA256
activate Crypto
Crypto -> Crypto : bytesToHex
activate Crypto
Crypto --> Crypto
deactivate Crypto
Crypto --> UserModel
deactivate Crypto
UserModel --> SignupServlet : save account
deactivate UserModel
ModelBase -> Database : save account
activate Database
Database --> ModelBase : saved
deactivate Database
return : login screen
@enduml