@startuml
actor Actor
Actor -> CheckAuthServlet : login request
activate CheckAuthServlet
Actor -> CheckAccountServlet : find user name
activate CheckAccountServlet
CheckAccountServlet -> UserModel : find name
activate UserModel

UserModel -> ModelBase : connection
activate ModelBase
ModelBase -> Database : find account
activate Database
Database --> ModelBase
deactivate Database
ModelBase --> UserModel
deactivate ModelBase
UserModel --> CheckAccountServlet : check authentication
deactivate UserModel


' create GoogleReCaptcha
CheckAuthServlet -> GoogleReCaptcha : call
activate GoogleReCaptcha
GoogleReCaptcha --> CheckAuthServlet
deactivate GoogleReCaptcha
' create UserModel
CheckAuthServlet -> UserModel : call
activate UserModel
UserModel --> CheckAuthServlet
deactivate UserModel
CheckAuthServlet -> GoogleReCaptcha : checkCaptcha
activate GoogleReCaptcha
GoogleReCaptcha -> GoogleReCaptcha : () ->
activate GoogleReCaptcha
GoogleReCaptcha --> GoogleReCaptcha
deactivate GoogleReCaptcha
GoogleReCaptcha --> CheckAuthServlet
deactivate GoogleReCaptcha
CheckAuthServlet -> UserModel : getStringToValidUser
activate UserModel
UserModel -> ModelBase : connection
activate ModelBase
ModelBase -> Database : find account
activate Database
Database --> ModelBase
deactivate Database
ModelBase --> UserModel
deactivate ModelBase
UserModel -> Crypto : SHA256
activate Crypto
Crypto -> Crypto : bytesToHex
activate Crypto
Crypto --> Crypto
deactivate Crypto
Crypto --> UserModel
deactivate Crypto
UserModel --> CheckAuthServlet : check user status
deactivate UserModel
' create UserModel
CheckAuthServlet -> UserModel : call
activate UserModel
UserModel --> CheckAuthServlet
deactivate UserModel
CheckAuthServlet -> UserModel : getByUsername
activate UserModel
UserModel -> ModelBase : connection
activate ModelBase
ModelBase --> UserModel
deactivate ModelBase
UserModel --> CheckAuthServlet : check user authentication
deactivate UserModel
Actor -> LoginServlet : request login
activate LoginServlet
LoginServlet --> Actor : set session for account
deactivate LoginServlet
return
@enduml